### ISSUE TITLE
Problems in IDE with duplicated actuator

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#1177]
## Situation
When I start SecHub server inside my IDE (eclipse) with

```
-Dspring.profiles.active=mocked_products,h2,integrationtest
-Dsechub.server.debug=false
-Dsechub.storage.sharedvolume.upload.dir=temp
-Dsechub.targettype.detection.intranet.hostname.endswith=intranet.example.org
-Dsechub.config.trigger.nextjob.initialdelay=0
-Dsechub.storage.sharedvolume.upload.dir=/home/username/sechub-data/upload
-Dsechub.development.webdesignmode.enabled=true

```
And executing `JobScenario2IntTest` I got an Illegal argument exception when second batch job is executed:
```
Failed to register Collector of type MicrometerCollector: 
The Collector exposes the same name multiple times: spring_batch_job_active_seconds
```
But when integration tests were executed by github actions via gradle the tests did NOT fail.
**So gradle and eclipse IDE run do differ here!**

## Environment
I tested with
- Commit 7e8611ad from branch `develop`
  (Spring Boot 2.6.4)
- Commit 26e197b2 from branch `feature-1098-...`
- Java 8, Java 11
- Eclipse 2021-12
- Eclipse 2022-03
- Eclipse project setup done by gradle call
  `./gradlew cleanEclipse clipse` and a refresh inside eclipse IDE
- Gradle 7.4
- Linux

Always the first test works, after the job has been created, all other tests do fail, because on server side the mentioned exception happens. 
After this it's no longer possible to execute any job test from IDE without restarting the integration test server launch again.

## Wanted
Shall work again in eclipse - this is big problem and slows down development.

### When? 
- After every job this happens
   After the first job has been processed, the problem appears on server side. Means even on first (succesful) test!

### How is the server started in eclipse?
I inspected the properties of the server launch in eclipse  (for commit 26e197b2)  ... and I found something very odd (I added some new lines here and it's not the full java command, but it shows the problem):
![image](https://user-images.githubusercontent.com/11644753/161005843-9fd5f3e2-5b10-45c5-9473-97cb9c334841.png)

There are two different micrometer-prometheus jars inside the classpath:
```
micrometer-registry-prometheus-1.8.3.jar
micrometer-registry-prometheus-1.7.2.jar
```

Looking at the depdencies of `sechub-server` I found:
![image](https://user-images.githubusercontent.com/11644753/161007832-e94f8b30-02f1-4567-b620-cc9590d7ed5a.png)

So inside gradle the library version is updated from 1.7.2 to 1.8.3 (and so should only use 1.8.3)

But where comes the 1.7.2?
Reason found:
![image](https://user-images.githubusercontent.com/11644753/161009387-bcb06bc4-924e-4050-8c69-8d433060d839.png)
****

## Solution
The problem is, that for eclipse .classpath generation the gradle eclipse plugin does use not the commonly used jar version, but the project defined one.

I am not sure if 
Change `build.gradle` part to `implementation 'io.micrometer:micrometer-registry-prometheus'

**Comment by de-jcup** [comment]
Here the full stacktrace:

```
2022-03-30 17:21:40.442 DEBUG 6123 --- [xecutor_thread4] c.m.s.d.a.j.JobInformationCreateService  : creating a new job information entry for project=s02_0001project1, job=44fdf031-34f7-4902-ab50-bc4bc024e118
Exception in thread "async-job-launcher1" java.lang.IllegalArgumentException: Failed to register Collector of type MicrometerCollector: The Collector exposes the same name multiple times: spring_batch_job_active_seconds
    at io.prometheus.client.CollectorRegistry.assertNoDuplicateNames(CollectorRegistry.java:71)
    at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:51)
    at io.prometheus.client.Collector.register(Collector.java:308)
    at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$applyToCollector$16(PrometheusMeterRegistry.java:479)
    at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
    at io.micrometer.prometheus.PrometheusMeterRegistry.applyToCollector(PrometheusMeterRegistry.java:475)
    at io.micrometer.prometheus.PrometheusMeterRegistry.newLongTaskTimer(PrometheusMeterRegistry.java:288)
    at io.micrometer.core.instrument.MeterRegistry$More.lambda$longTaskTimer$0(MeterRegistry.java:884)
    at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:620)
    at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:569)
    at io.micrometer.core.instrument.MeterRegistry.access$600(MeterRegistry.java:78)
    at io.micrometer.core.instrument.MeterRegistry$More.longTaskTimer(MeterRegistry.java:882)
    at io.micrometer.core.instrument.LongTaskTimer$Builder.register(LongTaskTimer.java:408)
    at io.micrometer.core.instrument.composite.CompositeLongTaskTimer.registerNewMeter(CompositeLongTaskTimer.java:98)
    at io.micrometer.core.instrument.composite.CompositeLongTaskTimer.registerNewMeter(CompositeLongTaskTimer.java:30)
    at io.micrometer.core.instrument.composite.AbstractCompositeMeter.add(AbstractCompositeMeter.java:66)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at java.util.Collections$SetFromMap.forEach(Collections.java:5530)
    at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$0(CompositeMeterRegistry.java:65)
    at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lock(CompositeMeterRegistry.java:184)
    at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$1(CompositeMeterRegistry.java:65)
    at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:630)
    at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:569)
    at io.micrometer.core.instrument.MeterRegistry.access$600(MeterRegistry.java:78)
    at io.micrometer.core.instrument.MeterRegistry$More.longTaskTimer(MeterRegistry.java:882)2022-03-30 17:21:40.455 DEBUG 6123 --- [xecutor_thread4] c.m.s.d.a.j.JobInformationCreateService  : saved new job information entry uuid=s02_0001project1 - for project=44fdf031-34f7-4902-ab50-bc4bc024e118, job=0c2353d5-347b-44e0-9f35-815147efe3e1,

    at io.micrometer.core.instrument.LongTaskTimer$Builder.register(LongTaskTimer.java:408)
    at org.springframework.batch.core.metrics.BatchMetrics.createLongTaskTimer(BatchMetrics.java:88)
    at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:304)
    at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:149)
    at java.lang.Thread.run(Thread.java:748)

```
