### ISSUE TITLE
Developer-Admin-UI jar does not work as standalone application anymore

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#1389]
## Problem
Commands to reproduce:
```bash
./gradlew buildDeveloperAdminUI
cp sechub-developertools/build/libs/sechub-developer-admin-ui-0.0.0.jar ~
cd ~
export SECHUB_ADMIN_APITOKEN=my-api-token
export SECHUB_ADMIN_USERID=my-user
export SECHUB_ADMIN_SERVER=localhost
export SECHUB_ADMIN_SERVER_PORT=8443
export SECHUB_ADMIN_ENVIRONMENT=test
java -jar ~/sechub-developer-admin-ui-0.0.0.jar
```
Java run fails with this output:
```
10:57:59.085 [Finalizer] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection manager is shutting down
10:57:59.087 [Finalizer] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection manager shut down
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.mercedesbenz.sechub.integrationtest.internal.MockData.getCombination(MockData.java:77)
        at com.mercedesbenz.sechub.integrationtest.internal.MockData.getTarget(MockData.java:69)
        at com.mercedesbenz.sechub.integrationtest.api.IntegrationTestMockMode.<init>(IntegrationTestMockMode.java:77)
        at com.mercedesbenz.sechub.integrationtest.api.IntegrationTestMockMode.<clinit>(IntegrationTestMockMode.java:20)
        at com.mercedesbenz.sechub.developertools.admin.ui.CommandUI.createIntegrationTestServerMenu(CommandUI.java:440)
        at com.mercedesbenz.sechub.developertools.admin.ui.CommandUI.createMainMenu(CommandUI.java:204)
        at com.mercedesbenz.sechub.developertools.admin.ui.CommandUI.<init>(CommandUI.java:154)
        at com.mercedesbenz.sechub.developertools.admin.ui.DeveloperAdministrationUI.start(DeveloperAdministrationUI.java:90)
        at com.mercedesbenz.sechub.developertools.admin.ui.DeveloperAdministrationUI.main(DeveloperAdministrationUI.java:27)
Caused by: java.lang.IllegalStateException: Testcase corrupt: Cannot read test file /home/myuser/../sechub-other/mockdata/mockdata_setup.json
        at com.mercedesbenz.sechub.test.TestFileReader.loadTextFile(TestFileReader.java:31)
        at com.mercedesbenz.sechub.test.TestFileReader.loadTextFile(TestFileReader.java:12)
        at com.mercedesbenz.sechub.integrationtest.internal.MockedAdapterSetupAccess.<init>(MockedAdapterSetupAccess.java:21)
        at com.mercedesbenz.sechub.integrationtest.internal.MockedAdapterSetupAccess.<clinit>(MockedAdapterSetupAccess.java:16)
        ... 9 more
Caused by: java.io.FileNotFoundException: ../sechub-other/mockdata/mockdata_setup.json (Datei oder Verzeichnis nicht gefunden)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at com.mercedesbenz.sechub.test.TestFileReader.loadTextFile(TestFileReader.java:18)
        ... 12 more
```

**Comment by de-jcup** [comment]
The main problem is, that we do not ship the integration test resource files (and we do not want to do this). For development we assume we are inside the developer IDE/git repository and `/home/myuser/../sechub-other/mockdata/mockdata_setup.json` is calculated.

But even when the file is not available, the other menu entries (without special mock integration test actions) must still work.

**Comment by de-jcup** [comment]
With last commit, the DAUI does alwas work. If the mock json file is not found, the test data sub menu will contain a replacement error action which describes the problem. But all other action will work as expected.
