### ISSUE TITLE
Integrationtests fail when using non-default ports

### ISSUE THREAD

**Issue by sven-dmlr** [mercedes-benz/sechub#1716]
## Problem:
Integrationtests fail when defining alternative ports.

Example (fails every time for me):
```
./gradlew integrationtest -Psechub.integrationtest.serverport=8292 -Psechub.integrationtest.pdsport=8592
```

Please check and fix.

**Comment by de-jcup** [comment]
An example output of one of the failing tests here:

```java
com.mercedesbenz.sechub.integrationtest.api.IntegrationTestSetup$IntegrationTestServerNotFoundException: The integration test PDS is not running. Cannot execute test. Build is alive url was:https://localhost:8444/api/anonymous/integrationtest/alive
Time was:2022-11-07T21:37:28.481118
	at app//com.mercedesbenz.sechub.integrationtest.api.IntegrationTestSetup.assertTestPDSRunning(IntegrationTestSetup.java:375)
	at app//com.mercedesbenz.sechub.integrationtest.api.IntegrationTestSetup.assertNecessaryTestServersRunning(IntegrationTestSetup.java:363)
	at app//com.mercedesbenz.sechub.integrationtest.api.IntegrationTestSetup$IntegrationTestStatement.evaluate(IntegrationTestSetup.java:171)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base@11.0.16/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.16/java.lang.Thread.run(Thread.java:829)
```

**Comment by de-jcup** [comment]
The Jenkins files do currently do set

```
SERVER_PORT= getJenkinsExecutorPort(8243)
PDS_PORT= getJenkinsExecutorPort(8543)
```

The call of 
```
 callGradleWrapper("integrationtest -Psechub.integrationtest.serverport=${env.SERVER_PORT} -Psechub.integrationtest.pdsport=${env.PDS_PORT}")
```
did use this settings to start PDS and SecHub server per script but did NOT change env settings. 
Instead, the env variables from the jenkins build setup were used at execution time.

So a local build by maven does currently NOT setup the ENV variables. And ENV variables are used by `TestPortProvider` to determine test ports etc.

Maybe the jenkins behaviour has changed as well here and the environment variables are no longer given to gradle tasks.

**Comment by de-jcup** [comment]
The main reason for the problems was the environment variables - they were no longer passed through the gradle processes. It seems there has something changed in the gradle versions.

This is not only a problem for integration tests, but also for wiremock tests (and even s3mock testing).
