### ISSUE TITLE
Fix problem of failing FileUploadSizeScenario2IntTest on S3 storage

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#1780]
## Situation
In  integration test `FileUploadSizeScenario2IntTest` the test method `when_binaries_tarfile_exceeds_NOT_max_bin_file_size_file_is_uploaded` fails on S3 usage.

The problematic part is here:
```java
assertEquals("Fetched file size not as expected for " + data.fileNameAtServerSide + " !", realFileSizeInBytes, fetchedSize);
```

The problem happens only on S3 usage, not when we use a network share volume.
It happens on build servers and also on local machines.

### Wanted
Find a solution...

**Comment by de-jcup** [comment]
The (reduced) test part is:
```java
File downloadedFile = TestAPI.getFileUploaded(PROJECT_1, jobUUID, data.fileNameAtServerSide);

long realFileSizeInBytes = downloadedFile.length();

File downloadedFileSizeFile = TestAPI.getFileUploaded(PROJECT_1, jobUUID, data.fileNameAtServerSide + ".filesize");

String fetchedSizeAsString = TestFileReader.loadTextFile(downloadedFileSizeFile);
long fetchedSize = Long.parseLong(fetchedSizeAsString);

assertEquals("Fetched file size not as expected for " + data.fileNameAtServerSide + " !", realFileSizeInBytes, fetchedSize);
            
``` 
The output from test is:

```java
java.lang.AssertionError: Fetched file size not as expected for binaries.tar ! expected:<7848> but was:<307199>
    at org.junit.Assert.fail(Assert.java:89)
    at org.junit.Assert.failNotEquals(Assert.java:835)
    at org.junit.Assert.assertEquals(Assert.java:647)
    at com.mercedesbenz.sechub.integrationtest.scenario2.FileUploadSizeScenario2IntTest.testErrorOrUploadDoneAsExpected(FileUploadSizeScenario2IntTest.java:243)
    at com.mercedesbenz.sechub.integrationtest.scenario2.FileUploadSizeScenario2IntTest.handleBinariesUpload(FileUploadSizeScenario2IntTest.java:212)
    at com.mercedesbenz.sechub.integrationtest.scenario2.FileUploadSizeScenario2IntTest.when_binaries_tarfile_exceeds_NOT_max_bin_file_size_file_is_uploaded(FileUploadSizeScenario2IntTest.java:77)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
    at com.mercedesbenz.sechub.integrationtest.api.IntegrationTestSetup$IntegrationTestStatement.evaluate(IntegrationTestSetup.java:229)
    at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
    at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by de-jcup** [comment]
So my first analyse was wrong - the filesize inside the text file uploaded to the s3 bucket does contain the expected size! So the input stream handling (and size calculation )is correct!

**Comment by de-jcup** [comment]
This is related to #1716 - while doing the fixes here, the problem became visible.
As long as #1782 is not done, it can be easy to check the uploaded file and whats happening.

**Comment by de-jcup** [comment]
Found the problem. `IntegrationTestServerRestController.getUploadedFile` had a problem inside and did not download complete files when S3 - see commit message for details
