### ISSUE TITLE
Test JRE Linux installer Adoptium

### ISSUE THREAD

**Issue by Jeeppler** [mercedes-benz/sechub#1794]
Test the JRE Linux installer for Adoptium: https://github.com/adoptium/installer/issues/430.

**Comment by ascheman** [comment]
As part of my work on adoptium/installer#430 a preliminary implementation of Debian installers for JREs 8, 11, 17, and 19 are now available from https://github.com/ascheman-adoptium/installer/tree/feature/430-jre-installer-debian 

Please test the resulting `.deb` packages in your context and give feedback to me and the Adoptium team (@smlambert), in particular if you run into problems, @Jeeppler

**Comment by Jeeppler** [comment]
@ascheman thank you, I will give it a try.

**Comment by Jeeppler** [comment]
@ascheman

# Debian Smoke Tests

What I tested so far is to check if the packages for product_version (Java version) `8, 11, 17 and 19` can be build and installed into a Debian environment. 

## Steps

1. Build the Debian package using:

    ~~~
    ./gradlew clean packageJreDebian checkJreDebian --parallel -PPRODUCT=temurin -PPRODUCT_VERSION=<version> -PARCH=amd64
   ~~~

2. Copied the build from `linux/jre/debian/build/ospackage` and put it in a folder with a Debian Dockerfile (using debian:11-slim).
3. Started the container. While building the container the Temurin Debian `dep` and `adoptium-ca-certificates_1.0.1-1_all.deb` get copied into the container. In addition, the following dependencies are installed for temurin:

   ~~~
   apt install --assume-yes java-common libasound2 libfontconfig1 libfreetype6 libx11-6 libxext6 libxi6 libxrender1 libxtst6 fonts-dejavu
   ~~~

    The adoptium ca-certificates package needs the following dependencies:

    ~~~
    apt install --assume-yes p11-kit ca-certificates
    ~~~

4. Install both via `dpkg`. For example, for Temurin-17 (Java)
    ~~~
    dpkg -i adoptium-ca-certificates_1.0.1-1_all.deb temurin-17-jre_17.0.5+8_amd64.deb
    ~~~

5. Run `java version` to see what version is installed.

It worked for all packages:

- Temurin 8
- Temurin 11
- Temurin 17
- Temurin 19

without any problems.

Next, I will test Alpine and do a test with SecHub and the JRE packages to see whether SecHub works with JRE packages as well. The only version I cannot test is Temurin 8, because SecHub requires already Java 11 as a minimum version.

**Comment by Jeeppler** [comment]
## Alpine Smoke Tests

#### Steps

1. Build

~~~
DOCKER_BUILDKIT=1 ./gradlew clean packageJreAlpine checkJreAlpine --parallel -PPRODUCT=temurin -PPRODUCT_VERSION=8 -PARCH=amd64
~~~

2. Copied the build from linux/jre/alpine/build/ospackage and put it in a folder with a Alpine Dockerfile (using alpine:3.17).

3. Install packages

~~~
apk add --allow-untrusted temurin-8-jre-8.352.08-r0.apk
~~~

4. Run `java -version` to see what version is installed.

#### Results

Worked for all JRE versions:

* Temurin 8
* Temurin 11
* Temurin 17
* Temurin 19

**Comment by ascheman** [comment]
Meanwhile I have also added Red Hat builds: https://github.com/ascheman-adoptium/installer/tree/feature/430-jre-installer-redhat

Please note that all of my `feature/430-xxx` branches are followups debian->alpine-redhat (and I will soon add SuSE). So in the end there will be only one PR for all distros.

**Comment by ascheman** [comment]
> Meanwhile I have also added Red Hat builds: https://github.com/ascheman-adoptium/installer/tree/feature/430-jre-installer-redhat
> 
> Please note that all of my `feature/430-xxx` branches are followups debian->alpine-redhat (and I will soon add SuSE). So in the end there will be only one PR for all distros.

@Jeeppler I have now consolidated all changes to a single branch: https://github.com/ascheman-adoptium/installer/tree/feature/430-jre-installer

**Comment by ascheman** [comment]
JRE for SUsE should work as well, @Jeeppler. 

I will perform some additional clean up which shouldn't affect the created packages.
Please confirm your test results to adoptium/installer#430 as well to increase confidence in all of these changes.

**Comment by Jeeppler** [comment]
@ascheman I moved the smoke test comments to: adoptium/installer#430.

**Comment by Jeeppler** [comment]
I build the Alpine package as described in: https://github.com/adoptium/installer/issues/430#issuecomment-1403256583

I got the following error message for JRE 11 and 17:

~~~
org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.mercedesbenz.sechub.SecHubServerApplication.main(SecHubServerApplication.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:229)
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
	... 22 common frames omitted
Caused by: java.lang.IllegalArgumentException: standardService.connector.startFailed
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:238)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:282)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:213)
	... 24 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to start component [Connector[HTTP/1.1-8443]]
	at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:234)
	... 26 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at java.base/javax.crypto.Cipher.getInstance(Unknown Source)
	at java.base/sun.security.ssl.SSLCipher.isTransformationAvailable(Unknown Source)
	at java.base/sun.security.ssl.SSLCipher.<init>(Unknown Source)
	at java.base/sun.security.ssl.SSLCipher.<clinit>(Unknown Source)
	at java.base/sun.security.ssl.CipherSuite.<clinit>(Unknown Source)
	at java.base/sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuites(Unknown Source)
	at java.base/sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at java.base/java.security.Provider$Service.getImplClass(Unknown Source)
	at java.base/java.security.Provider$Service.getDefaultConstructor(Unknown Source)
	at java.base/java.security.Provider$Service.newInstanceOf(Unknown Source)
	at java.base/java.security.Provider$Service.newInstanceUtil(Unknown Source)
	at java.base/java.security.Provider$Service.newInstance(Unknown Source)
	at java.base/sun.security.jca.GetInstance.getInstance(Unknown Source)
	at java.base/sun.security.jca.GetInstance.getInstance(Unknown Source)
	at java.base/javax.net.ssl.SSLContext.getInstance(Unknown Source)
	at org.apache.tomcat.util.net.jsse.JSSESSLContext.<init>(JSSESSLContext.java:45)
	at org.apache.tomcat.util.net.jsse.JSSEUtil.initialise(JSSEUtil.java:105)
	at org.apache.tomcat.util.net.jsse.JSSEUtil.getImplementedProtocols(JSSEUtil.java:73)
	at org.apache.tomcat.util.net.SSLUtilBase.<init>(SSLUtilBase.java:92)
	at org.apache.tomcat.util.net.jsse.JSSEUtil.<init>(JSSEUtil.java:61)
	at org.apache.tomcat.util.net.jsse.JSSEUtil.<init>(JSSEUtil.java:56)
	at org.apache.tomcat.util.net.jsse.JSSEImplementation.getSSLUtil(JSSEImplementation.java:59)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:96)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:71)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:235)
	at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1227)
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1313)
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:614)
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1074)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	... 27 common frames omitted
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
	at java.base/javax.crypto.JceSecurity.<clinit>(Unknown Source)
	... 59 common frames omitted
Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited
	at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(Unknown Source)
	at java.base/javax.crypto.JceSecurity$1.run(Unknown Source)
	at java.base/javax.crypto.JceSecurity$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	... 60 common frames omitted
~~~

I installed the packages by copying them inside the container and later installing them with the following commands:

~~~
COPY copy/temurin-17-jre-17.0.5_p8-r0.apk /temurin-17-jre-17.0.5_p8-r0.apk
RUN apk add --allow-untrusted /temurin-17-jre-17.0.5_p8-r0.apk
~~~

**Comment by ascheman** [comment]
> I build the Alpine package as described in: [adoptium/installer#430 (comment)](https://github.com/adoptium/installer/issues/430#issuecomment-1403256583)
> 
> I got the following error message for JRE 11 and 17:
> 
> ```
> org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
...
> ```
> 
> I installed the packages by copying them inside the container and later installing them with the following commands:
> 
> ```
> COPY copy/temurin-17-jre-17.0.5_p8-r0.apk /temurin-17-jre-17.0.5_p8-r0.apk
> RUN apk add --allow-untrusted /temurin-17-jre-17.0.5_p8-r0.apk
> ```

There must be missing some steps of what you did to create this error, @Jeeppler? The installers do not contain Spring nor Tomcat. Could you provide the full Dockerfile or even the overall project somewhere?

**Comment by Jeeppler** [comment]
I used SecHub (this project) to test it with. You can find the `Alpine.dockerfile` here: https://github.com/mercedes-benz/sechub/blob/feature-1536-sechub-dockerfile-alpine/sechub-solution/docker/SecHub-Alpine.dockerfile.

The `Alpine.dockerfile` contains to main parts. First, a builder which either downloads, builds or copies SecHub into the container. Second, the runtime image which uses a JRE/JDK to run SecHub.

Currently, the Temurin-`apk` files are copied into the runtime image and then installed. Have a look: https://github.com/mercedes-benz/sechub/blob/feature-1536-sechub-dockerfile-alpine/sechub-solution/docker/SecHub-Alpine.dockerfile#L156.

SecHub is a Spring Boot Application using an embedded Tomcat Server.

I am actually not sure, why I get this exception: 

~~~
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
	at java.base/javax.crypto.JceSecurity.<clinit>(Unknown Source)
	... 59 common frames omitted
Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited
~~~

**Comment by Jeeppler** [comment]
## Debian SecHub Test

**Tests:**

* SecHub starts
* Scan with GoSec+PDS Solution

### Temurin 11 JRE

[x] SecHub starts
[x] Scan with GoSec+PDS Solution

### Temurin 17 JRE

[x] SecHub starts
[x] Scan with GoSec+PDS Solution

### Temurin 19 JRE

[x] SecHub starts
[x] Scan with GoSec+PDS Solution

## Conclusion

All tests were successfull. Temurin JRE packages 11, 17 and 19 work with the Spring Boot based application: SecHub.

**Comment by Jeeppler** [comment]
@ascheman I followed the official guide to install Temurin JDK for Alpine from the website: [Alpine Linux Instructions](https://adoptium.net/installation/linux/#_alpine_linux_instructions). I am seeing the same problems using the JDK as with the JRE builds (see previous [comment](https://github.com/mercedes-benz/sechub/issues/1794#issuecomment-1403290491)):

~~~
org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.mercedesbenz.sechub.SecHubServerApplication.main(SecHubServerApplication.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:229)
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:43)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
	... 22 common frames omitted
Caused by: java.lang.IllegalArgumentException: standardService.connector.startFailed
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:238)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:282)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:213)
	... 24 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to start component [Connector[HTTP/1.1-8443]]
	at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:234)
	... 26 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at java.base/javax.crypto.Cipher.getInstance(Cipher.java:546)
	at java.base/sun.security.ssl.SSLCipher.isTransformationAvailable(SSLCipher.java:511)
	at java.base/sun.security.ssl.SSLCipher.<init>(SSLCipher.java:500)
	at java.base/sun.security.ssl.SSLCipher.<clinit>(SSLCipher.java:82)
	at java.base/sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:65)
	at java.base/sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuites(SSLContextImpl.java:343)
	at java.base/sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:556)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at java.base/java.security.Provider$Service.getImplClass(Provider.java:1933)
	at java.base/java.security.Provider$Service.getDefaultConstructor(Provider.java:1964)
	at java.base/java.security.Provider$Service.newInstanceOf(Provider.java:1878)
	at java.base/java.security.Provider$Service.newInstanceUtil(Provider.java:1886)
	at java.base/java.security.Provider$Service.newInstance(Provider.java:1861)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:185)
	at org.apache.tomcat.util.net.jsse.JSSESSLContext.<init>(JSSESSLContext.java:45)
	at org.apache.tomcat.util.net.jsse.JSSEUtil.initialise(JSSEUtil.java:105)
	at org.apache.tomcat.util.net.jsse.JSSEUtil.getImplementedProtocols(JSSEUtil.java:73)
	at org.apache.tomcat.util.net.SSLUtilBase.<init>(SSLUtilBase.java:92)
	at org.apache.tomcat.util.net.jsse.JSSEUtil.<init>(JSSEUtil.java:61)
	at org.apache.tomcat.util.net.jsse.JSSEUtil.<init>(JSSEUtil.java:56)
	at org.apache.tomcat.util.net.jsse.JSSEImplementation.getSSLUtil(JSSEImplementation.java:59)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.createSSLContext(AbstractJsseEndpoint.java:96)
	at org.apache.tomcat.util.net.AbstractJsseEndpoint.initialiseSsl(AbstractJsseEndpoint.java:71)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:235)
	at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1227)
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1313)
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:614)
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1074)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	... 27 common frames omitted
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:119)
	... 59 common frames omitted
Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited
	at java.base/javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:333)
	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:110)
	at java.base/javax.crypto.JceSecurity$1.run(JceSecurity.java:107)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.base/javax.crypto.JceSecurity.<clinit>(JceSecurity.java:106)
	... 59 common frames omitted
~~~

**Comment by ascheman** [comment]
Due to the [latest release of Temurin](https://adoptium.net/temurin/releases/) of last week I had to calibrate the used JRE tarballs, @Jeeppler:
* 8u362
* 11.0.18
* 17.0.6
* 19.0.2

Meanwhile I raised a (hopefully) [final PR](https://github.com/adoptium/installer/pull/591).
Would you mind re-testing it again?

**Comment by Jeeppler** [comment]
@ascheman The new Temurin Alpine images still cause the `Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited`.

I figured out that I can set the policy using this parameter while starting SecHub: `-Djava.security.properties='/usr/lib/jvm/java-11-temurin-jre/conf/security/java.security'`.

However, now I get the following exception: `Caused by: java.security.NoSuchAlgorithmException: RSA KeyFactory not available`. I am still not sure why this happens. But my expectation would be that Debian and Alpine Temurin behave the same.

**Comment by ascheman** [comment]
> @ascheman The new Temurin Alpine images still cause the `Caused by: java.lang.SecurityException: Can't read cryptographic policy directory: unlimited`.
> 
> I figured out that I can set the policy using this parameter while starting SecHub: `-Djava.security.properties='/usr/lib/jvm/java-11-temurin-jre/conf/security/java.security'`.
> 
> However, now I get the following exception: `Caused by: java.security.NoSuchAlgorithmException: RSA KeyFactory not available`. I am still not sure why this happens. But my expectation would be that Debian and Alpine Temurin behave the same.
> 
> Shall I create a new issue for this?

I think the problem is the split up of the Alpine installers into two APKs. 
If you install both, cf. https://github.com/ascheman-adoptium/sechub/commit/99155bc0ee8552304527201176674d6f1bcb634e the problem disappears.

I still try to clarify what was the reason to split up the APKs since JDK-11 with Adoptium Temurin. 
If all else fails, we need to raise a bug ticket.

**Comment by Jeeppler** [comment]
@ascheman Thanks for looking into it. I will give it a try.

**Comment by ascheman** [comment]
@Jeeppler meanwhile the JRE installers are released and published to the [Adoptium Artifactory](https://adoptium.jfrog.io/ui/repos/tree/General/) (for all major architectures and the distros Alpine, Debian, Redhat and SuSE). So you could download from there as well. Installation documentation still needs to be written.

**Comment by Jeeppler** [comment]
@ascheman thanks, I will try them.

**Comment by Jeeppler** [comment]
@ascheman I tried it and I still get a SecurityException using the Alpine images:

~~~
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
  at java.base/javax.crypto.JceSecurity.<clinit>(Unknown Source)
  ... 57 common frames omitted
~~~

The installation command was:

~~~
wget -O /etc/apk/keys/adoptium.rsa.pub https://packages.adoptium.net/artifactory/api/security/keypair/public/repositories/apk
echo 'https://packages.adoptium.net/artifactory/apk/alpine/main' >> /etc/apk/repositories

apk add temurin-11-jre
~~~

**Comment by Jeeppler** [comment]
Successfully tested and all problems fixed.
