### ISSUE TITLE
LocalDateTime not correct handled by JSOnConverter in sechub-commons-model

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#1797]
## Situation
When getting a job info list about a project following is returned
```
  "page" : 0,
  "totalPages" : 4,
  "projectId" : "s19_0001project1",
  "content" : [ {
    "jobUUID" : "30ae32fc-618a-42e4-aac3-d534998921f2",
    "executedBy" : "s19_0001_user1",
    "created" : [ 2022, 12, 5, 17, 56, 2, 187721000 ],
    "ended" : [ 2022, 12, 5, 17, 56, 2, 390663000 ],
    "executionState" : "CANCEL_REQUESTED",
    "executionResult" : "FAILED"
  } ]
}
``` 

The local date is no longer in a ISO-8601 compatible way, but now always represented by an array.

### Problem 1
Readability suffers in outputs

### Problem 2
`JsonConverter.java` from sechub-commons-model is not/no longer able to handle `LocalDate` and other Java8 time stamps!

The jackson `JavaTimeModule` is not available inside commons-model and also not registered to the JSON converter mapper inside - so deserializing something with a local date inside does following:

``` java
com.mercedesbenz.sechub.commons.model.JSONConverterException: Was not able to convert com.mercedesbenz.sechub.commons.model.JSONConverterTestObject to JSON
	at com.mercedesbenz.sechub.commons.model.JSONConverter.toJSON(JSONConverter.java:88)
	at com.mercedesbenz.sechub.commons.model.JSONConverter.toJSON(JSONConverter.java:71)
	at com.mercedesbenz.sechub.commons.model.JSONConverterTest.iso8601_date_format_is_written(JSONConverterTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: com.mercedesbenz.sechub.commons.model.JSONConverterTestObject["time"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)
	at com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer.serialize(UnsupportedTypeSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4568)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3844)
	at com.mercedesbenz.sechub.commons.model.JSONConverter.toJSON(JSONConverter.java:83)
	... 71 more
```

### Problem 3
Why does #928 work? Maybe the default JSON converter from spring boot is used which does use the missing jackson module ?

## Wanted
- JSON converter must be able to read LocalDate, LocalDatetime etc. without any exceptions!
- If possible, change the code so we have readable ISO-8601 output again

## Solution
- Analyse problem (when did it happen, why etc. - Under suspect: Jackson lib update by spring boot update)
- Add jackson module `JavaDateTime` in mapper configuration
- Add jackson dependency to sechub-commons-model
- Add unit tests for local date time in `JsonConverterTest.java`
- Try to handle ISO-8601

**Comment by de-jcup** [comment]
There seems to be a lot of discussion about  issues with ISO 8601with jackson.

For example: https://bleepcoder.com/jackson-databind/263148247/iso8601dateformat-is-deprecated-but-replacement-is-unclear

**Comment by de-jcup** [comment]
In future there will be changes in jackson:
https://github.com/FasterXML/jackson-modules-java8 will be the only dependency to get local date working etc. But at the moment  we have still following situation:

```
runtimeClasspath - Runtime classpath of source set 'main'.
+--- com.fasterxml.jackson.core:jackson-core:2.13.4
|    \--- com.fasterxml.jackson:jackson-bom:2.13.4
|         +--- com.fasterxml.jackson.core:jackson-annotations:2.13.4 (c)
|         +--- com.fasterxml.jackson.core:jackson-core:2.13.4 (c)
|         +--- com.fasterxml.jackson.core:jackson-databind:2.13.4 -> 2.13.4.2 (c)
|         \--- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.4 (c)
+--- com.fasterxml.jackson.core:jackson-databind:2.13.4.2
|    +--- com.fasterxml.jackson.core:jackson-annotations:2.13.4
|    |    \--- com.fasterxml.jackson:jackson-bom:2.13.4 (*)
|    +--- com.fasterxml.jackson.core:jackson-core:2.13.4 (*)
|    \--- com.fasterxml.jackson:jackson-bom:2.13.4 (*)
+--- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.4
|    +--- com.fasterxml.jackson.core:jackson-core:2.13.4 (*)
|    +--- com.fasterxml.jackson.core:jackson-databind:2.13.4 -> 2.13.4.2 (*)
|    \--- com.fasterxml.jackson:jackson-bom:2.13.4 (*)
\--- project :sechub-commons-core
     \--- org.slf4j:slf4j-api:1.7.32
```

And inside spring boot (2.7.x): 
```
|    +--- org.springframework.boot:spring-boot-starter-json:2.7.8
|    |    +--- org.springframework.boot:spring-boot-starter:2.7.8 (*)
|    |    +--- org.springframework:spring-web:5.3.25
|    |    |    +--- org.springframework:spring-beans:5.3.25 (*)
|    |    |    \--- org.springframework:spring-core:5.3.25 (*)
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.4.2
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.13.4
|    |    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.4
|    |    |    |         +--- com.fasterxml.jackson.core:jackson-annotations:2.13.4 (c)
|    |    |    |         +--- com.fasterxml.jackson.core:jackson-core:2.13.4 (c)
|    |    |    |         +--- com.fasterxml.jackson.core:jackson-databind:2.13.4 -> 2.13.4.2 (c)
|    |    |    |         +--- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.4 (c)
|    |    |    |         +--- com.fasterxml.jackson.datatype:jackson-datatype-:2.13.4 (c)
|    |    |    |         +--- com.fasterxml.jackson.module:jackson-module-parameter-names:2.13.4 (c)
|    |    |    |         \--- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.13.4 (c)
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.13.4
|    |    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.4 (*)
|    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.4 (*)
|    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.4
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.13.4 (*)
|    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.4 -> 2.13.4.2 (*)
|    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.4 (*)
|    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.4
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.13.4 (*)
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.13.4 (*)
|    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.4 -> 2.13.4.2 (*)
|
```
Reading https://github.com/FasterXML/jackson-modules-java8
We need to use JavaTimeModule which is part of 
`com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.4`
so we need to add this as gradle dependency to `sechub-commons-model`.

**Comment by de-jcup** [comment]
## Definitions
### Patterns
We define 

`yyyy-MM-dd` as standard for our `LocalDate` serialization
`yyyy-MM-dd'T'HH:mm:ss.n'Z'` as standard for our `LocalDateTime` serialization

### Examples:
{"date":"2023-03-07"}
{"dateTime":"2023-03-07T17:13:33.293905000Z"}

These formats can be read by bash date function as well:
```
albert@somewhere:~$ date -d 2023-03-07T17:08:17.36804000Z --iso-8601=ns
2023-03-07T18:08:17,368040000+01:00
```
