### ISSUE TITLE
SecHubClient fails with AssertionError (Java <= 11)

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#2205]
## Situation
The `SystemTestFrameworkIntTest` (introduced in  #2092) does always fail on GitHub actions (this happens while developing #2092 but I raised an additional issue here, to clarify the problem)

```java
java.lang.AssertionError
	at java.net.http/jdk.internal.net.http.ResponseSubscribers$HttpResponseInputStream.read(ResponseSubscribers.java:408)
	at java.base/java.io.InputStream.readNBytes(InputStream.java:396)
	at java.base/java.io.InputStream.readAllBytes(InputStream.java:333)
	at com.mercedesbenz.sechub.api.internal.gen.AdminApi.getApiException(AdminApi.java:73)
	at com.mercedesbenz.sechub.api.internal.gen.AdminApi.adminFetchesExecutionProfileWithHttpInfo(AdminApi.java:1557)
	at com.mercedesbenz.sechub.api.internal.gen.AdminApi.adminFetchesExecutionProfile(AdminApi.java:1536)
	at com.mercedesbenz.sechub.api.SecHubClient.isExecutionProfileExisting(SecHubClient.java:166)
	at com.mercedesbenz.sechub.systemtest.runtime.SystemTestRuntimeLocalSecHubProductConfigurator.deleteExistingProfiles(SystemTestRuntimeLocalSecHubProductConfigurator.java:79)
...
```
## Analyze
It is a known bug in Java 11, was fixed only for Java >=14
https://bugs.openjdk.org/browse/JDK-8228970

### Switch to Java 17
For the upcoming update to Spring Boot 3 we already need Java 17.
So we could
- change the runtime for the build to Java 17
- change the compile level to Java 17 as well

### Replace JDK HTTP client usage with library
Change generator to use a dedicated library instead of JDK HTTP client

**Comment by de-jcup** [comment]
With #1736 we switched to Java 17- so this issue is now obsolete and I will close it.
