### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#2423]
## Situation

We have a flaky integration test: **ProductExecutorConfigurationScenario8IntTest**.

Sometimes we have following error:

```java
java.lang.NullPointerException: Cannot invoke "java.util.UUID.toString()" because "sechubJobUUID" is null
	at com.mercedesbenz.sechub.test.SecHubTestURLBuilder.buildAdminDownloadsZipFileContainingFullScanDataFor(SecHubTestURLBuilder.java:313)
	at com.mercedesbenz.sechub.integrationtest.api.AsUser.downloadFullScanDataFor(AsUser.java:844)
	at com.mercedesbenz.sechub.integrationtest.scenario8.ProductExecutorConfigurationScenario8IntTest.two_profiles_with_same_config_inside_for_same_product_result_in_scanlog_with_one_metadata_and_result_entry_for_product(ProductExecutorConfigurationScenario8IntTest.java:168)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.mercedesbenz.sechub.integrationtest.api.IntegrationTestSetup$IntegrationTestStatement.evaluate(IntegrationTestSetup.java:229)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

The test source part is:
```java
        createOrResetProfile(profileId2);

        as(SUPER_ADMIN).
            addConfigurationToProfile(profileId2,config1UUID).
            addProjectsToProfile(profileId2, PROJECT_1);

        /* execute */
        ExecutionResult result = as(USER_1).createWebScanAndFetchScanData(PROJECT_1);

        /* test */
        File zipfile = as(SUPER_ADMIN).downloadFullScanDataFor(result.getSechubJobUUID());
```

And the execution result has sometimes no SecHub job uuid which leads to `NPE`.

**Comment by de-jcup** [comment]
After analyzing the data it became clear that the `AuthUpdateUserApiTokenService.updateAPIToken()` call was not able to update the api token, because of an Optimistic Lock Exception (race condition with other update).

There are multiple problems:
- first of all, if the api token update fails the test should fail with something like "I was not able to update token for user:xxx"
- the token update mechanism is not resilient: If an optimistic lock happens it should simply reload the entity and update the token again
