### ISSUE TITLE
Fix problems with wildcards inside web scan header configuration `onlyForUrls`

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#2442]
## Situation
With #2174 we introduced a wildcard `<*>` for filtering urls by `onlyForUrls`.

We wrote an integration test, but in real server deployment the communication between SecHub client and SecHub server failed when creating a new SecHub job.

The failure message contained information that it is not a valid url - but the text did not contain `<*>` but instead `lt;*` - means html escaped

## Wanted
Find the problem and fix it.

## Solution
- Enhance / or write new integration test to reprocude the problem (and have a failing build)
- Fix the problem

**Comment by de-jcup** [comment]
The integration test `PDSWebScanJobScenario12IntTest` does now use SecHub client and reproduces the situation: It does currently fail with:

```java
java.lang.AssertionError: Not exit code 0 but:5 , last output line was:body={"status":400,"error":"Bad Request","message":"Validation failed for object='secHubConfiguration'. Error count: 2","details":["The URL for a HTTP header is not a valid URL! OnlyForUrls defined URL: https://demo.example.org/myapp/upload/&lt;*>/ is not a valid URL.","The URL for a HTTP header is not a valid URL! OnlyForUrls defined URL: https://demo.example.org/myapp/&lt;*>/special/ is not a valid URL."],"timeStamp":"Thu Aug 03 15:44:13 CEST 2023"}
	at org.junit.Assert.fail(Assert.java:89)
	at com.mercedesbenz.sechub.integrationtest.api.WithSecHubClient.startAsynchronScanFor(WithSecHubClient.java:268)
	at com.mercedesbenz.sechub.integrationtest.api.WithSecHubClient.startAsynchronScanFor(WithSecHubClient.java:293)
	at com.mercedesbenz.sechub.integrationtest.api.WithSecHubClient.startAsynchronScanFor(WithSecHubClient.java:277)
	at com.mercedesbenz.sechub.integrationtest.scenario12.PDSWebScanJobScenario12IntTest.pds_web_scan_has_expected_info_finding_with_given_target_url_and_product2_level_information_and_sechub_web_config_parts(PDSWebScanJobScenario12IntTest.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.mercedesbenz.sechub.integrationtest.api.IntegrationTestSetup$IntegrationTestStatement.evaluate(IntegrationTestSetup.java:229)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)


```
