### ISSUE TITLE
Failing integration test for system tests does not show origin failure but system test NPE

### ISSUE THREAD

**Issue by zigfridus** [mercedes-benz/sechub#2561]
## Situation
In case of running `./sdc.sh --integrationtest-systemtest`  the next errors apears:
`SystemTestFrameworkIntTest > even_integration_test_setup_can_be_tested_codescan_source_only_and_gen_example() FAILED
    java.lang.NullPointerException at SystemTestFrameworkIntTest.java:146`
`SystemTestFrameworkIntTest > even_integration_test_setup_can_be_tested__codescan_with_binary_and_sources() FAILED
    java.lang.NullPointerException at SystemTestFrameworkIntTest.java:239`

<details>
  <summary>Details</summary>
even_integration_test_setup_can_be_tested__codescan_with_binary_and_sources()
java.lang.NullPointerException: Cannot invoke "com.mercedesbenz.sechub.api.SecHubReport.getTrafficLight()" because "report" is null
	at com.mercedesbenz.sechub.systemtest.runtime.testengine.SystemTestRuntimeTestAssertion.handleSecHubAssert(SystemTestRuntimeTestAssertion.java:42)
	at com.mercedesbenz.sechub.systemtest.runtime.testengine.SystemTestRuntimeTestAssertion.handleSecHubAsserts(SystemTestRuntimeTestAssertion.java:33)
	at com.mercedesbenz.sechub.systemtest.runtime.testengine.SystemTestRuntimeTestAssertion.assertTest(SystemTestRuntimeTestAssertion.java:23)
	at com.mercedesbenz.sechub.systemtest.runtime.testengine.SystemTestRuntimeTestEngine.assertTest(SystemTestRuntimeTestEngine.java:86)
	at com.mercedesbenz.sechub.systemtest.runtime.testengine.SystemTestRuntimeTestEngine.runTest(SystemTestRuntimeTestEngine.java:73)
	at com.mercedesbenz.sechub.systemtest.runtime.SystemTestRuntime.runAfterInitialization(SystemTestRuntime.java:122)
	at com.mercedesbenz.sechub.systemtest.runtime.SystemTestRuntime.run(SystemTestRuntime.java:73)
	at com.mercedesbenz.sechub.systemtest.SystemTestAPI.runSystemTests(SystemTestAPI.java:65)
	at com.mercedesbenz.sechub.systemtest.SystemTestFrameworkIntTest.even_integration_test_setup_can_be_tested__codescan_with_binary_and_sources(SystemTestFrameworkIntTest.java:239)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:110)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:85)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
   `
    
even_integration_test_setup_can_be_tested_codescan_source_only_and_gen_example()
java.lang.NullPointerException: Cannot invoke "com.mercedesbenz.sechub.api.SecHubReport.getTrafficLight()" because "report" is null
	at com.mercedesbenz.sechub.systemtest.runtime.testengine.SystemTestRuntimeTestAssertion.handleSecHubAssert(SystemTestRuntimeTestAssertion.java:42)
	at com.mercedesbenz.sechub.systemtest.runtime.testengine.SystemTestRuntimeTestAssertion.handleSecHubAsserts(SystemTestRuntimeTestAssertion.java:33)
	at com.mercedesbenz.sechub.systemtest.runtime.testengine.SystemTestRuntimeTestAssertion.assertTest(SystemTestRuntimeTestAssertion.java:23)
	at com.mercedesbenz.sechub.systemtest.runtime.testengine.SystemTestRuntimeTestEngine.assertTest(SystemTestRuntimeTestEngine.java:86)
	at com.mercedesbenz.sechub.systemtest.runtime.testengine.SystemTestRuntimeTestEngine.runTest(SystemTestRuntimeTestEngine.java:73)
	at com.mercedesbenz.sechub.systemtest.runtime.SystemTestRuntime.runAfterInitialization(SystemTestRuntime.java:122)
	at com.mercedesbenz.sechub.systemtest.runtime.SystemTestRuntime.run(SystemTestRuntime.java:73)
	at com.mercedesbenz.sechub.systemtest.SystemTestAPI.runSystemTests(SystemTestAPI.java:65)
	at com.mercedesbenz.sechub.systemtest.SystemTestFrameworkIntTest.even_integration_test_setup_can_be_tested_codescan_source_only_and_gen_example(SystemTestFrameworkIntTest.java:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:110)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:85)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
</details>

## Wanted
`./sdc.sh --integrationtest-systemtest`  must run without errors.

@de-jcup

**Comment by Jeeppler** [comment]
@zigfridus thanks for opening the issue.

**Comment by Jeeppler** [comment]
@de-jcup please have a look at this. I was able to reproduce the same issue.

**Comment by de-jcup** [comment]
@zigfridus : Sorry for the late response and thank you for creating the issue. I will inspect the problem.

**Comment by Jeeppler** [comment]
The local test results from my machine: [systemtest-failure.zip](https://github.com/mercedes-benz/sechub/files/12819968/systemtest-failure.zip)

Git: commit 602f3805e8e7c7e9560f97490197511322a8099d

**Comment by Jeeppler** [comment]
Local test results based on `feature-345-summary-in-reports` branch by @zigfridus:  [systemtest-failure3-with-npe.zip](https://github.com/mercedes-benz/sechub/files/12820195/systemtest-failure3-with-npe.zip)

Git: commit e22c4838fbace6fa7f477a0a9fa0713445a22329

**Comment by Jeeppler** [comment]
@zigfridus please merge the latest changes into your branch and run the tests again on GitHub Actions (your side).

**Comment by zigfridus** [comment]
@de-jcup @Jeeppler 

I ran the tests again on GitHub Actions. Unfortunately they failed again with the same NPE:
`BUILD FAILED in 51s
[com.mercedesbenz.sechub.systemtest.SystemTestFrameworkIntTest::even_integration_test_setup_can_be_tested_codescan_source_only_and_gen_example()]
[com.mercedesbenz.sechub.systemtest.SystemTestFrameworkIntTest::even_integration_test_setup_can_be_tested__codescan_with_binary_and_sources()]`
[failed tests](https://github.com/zigfridus/sechub/actions/runs/6429764989/job/17460820482#step:10:167)

Looks like the problem is on my side only.
I could try to update system tests by myself, but I need the set up guide of Eclipse for debugging the system tests.

Thanks

**Comment by Jeeppler** [comment]
@zigfridus I can reproduce the issue, if I am building on your branch. Additionally, I can confirm, that after merging develop the problem still persists on your branch (commit: 690dbad771d827c218abef7cfd6be96f9a1154f7).

**Comment by zigfridus** [comment]
@Jeeppler How can I help to solve this problem?

**Comment by de-jcup** [comment]
@Jeeppler, @zigfridus :
After I have fixed 
- https://github.com/mercedes-benz/sechub/issues/2577

I will checkout the branch from @zigfridus directly into my IDE and inspect the problem.

**Comment by de-jcup** [comment]
The problem is reproducable locally inside IDE (eclipse):

- Checked out branch `zigfridus/feature-345-summary-in-reports`
- imported into Eclipse via EGradle
- Started from IDE:
  - local SecHub server (integration test mode)
  - local PDS server (integration test mode)
- Started Junit test from IDE SystemTestFrameworkIntTest#even_integration_test_setup_can_be_tested_codescan_source_only_and_gen_example with `-Dsechub.integrationtest.running=true`
- Test fails with NPE

## Details:
The main problem is that there is another not tracked exception. when test start in IDE, we got the NPE from unit test:
``` java
java.lang.NullPointerException: Cannot invoke "com.mercedesbenz.sechub.api.SecHubReport.getTrafficLight()" because "report" is null
	at com.mercedesbenz.sechub.systemtest.runtime.testengine.SystemTestRuntimeTestAssertion.handleSecHubAssert(SystemTestRuntimeTestAssertion.java:42)
```
but inside console (for unit test ) we see:

``` java
09:26:44.718 [main] ERROR com.mercedesbenz.sechub.systemtest.runtime.testengine.SystemTestRuntimeTestEngine - Test: test1 failed: Was not able to launch SecHub job
com.mercedesbenz.sechub.api.SecHubClientException: Download SecHub report (JSON) - userDownloadsJobReport call failed with: 500 - {"status":500,"error":"Internal Server Error","details":[],"timeStamp":"Mon Oct 09 09:26:44 CEST 2023"}
	at com.mercedesbenz.sechub.api.DefaultSecHubClient.createClientException(DefaultSecHubClient.java:448)
	at com.mercedesbenz.sechub.api.DefaultSecHubClient.runOrFail(DefaultSecHubClient.java:455)
```

The server side error in detail is:
```java
2023-10-09 09:26:44.705 ERROR 12406 --- [0.1-8443-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.TreeMap.getEntry(TreeMap.java:345)
	at java.base/java.util.TreeMap.get(TreeMap.java:279)
	at com.mercedesbenz.sechub.commons.model.SecHubReportMetaDataSummaryDetails.detailsFiller(SecHubReportMetaDataSummaryDetails.java:28)
	at com.mercedesbenz.sechub.commons.model.SecHubReportMetaDataSummaryDetails.detailsHelper(SecHubReportMetaDataSummaryDetails.java:21)

```

@zigfridus : This means that your implementation produces a NPE on server side, which leads to to failing SecHub system test. Please fix this at your side. I will enhance the failure mechanism inside sechub system tests to provide better information inside the unit test outputs. I will do this via this issue. 

Remark: Please name the methods and variables different: `detailsFiller`, `helperMap` and `detailsHelper` are not clear what the names stands for exactly. Also in java method names should be some kind of verbs - explaining what it does (e.g. "fill() or update()" etc.
- I would suggest to call `helperMap` instead `summaryDetails`.
- rename `reportScanHelper` method to `calculateSummaryMetaData()`

**Comment by Jeeppler** [comment]
`helperMap` is very generic. `summaryDetails` is clearer. However, as @de-jcup mentioned a verb would be nice.

**Comment by zigfridus** [comment]
@de-jcup 
Thank you for resolving this issue.
