### ISSUE TITLE
Integration tests have growing test scenario failure when server restart necessary (with postgres DB)

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#3322]
## Situation
When I start `JobScenario2IntTest` and have following scenario:
- using a local postgres DB
- a running SecHub server in integration test mode (with postgres as DB)

the first run will work.

Now we just terminate and relaunch the SecHub server (same setup) and execute the test again (postgres database is still running and has old test data inside).
This leads to following problem:

```
java.lang.AssertionError: s02_0001_owner1 found!
	at com.mercedesbenz.sechub.integrationtest.api.AbstractAssert.expectHttpClientError(AbstractAssert.java:34)
	at com.mercedesbenz.sechub.integrationtest.api.AssertUser.doesNotExist(AssertUser.java:52)
	at com.mercedesbenz.sechub.integrationtest.api.AssertUser.doesNotExist(AssertUser.java:35)
	at com.mercedesbenz.sechub.integrationtest.internal.ScenarioInitializer.createUser(ScenarioInitializer.java:103)
	at com.mercedesbenz.sechub.integrationtest.scenario2.Scenario2.initializeTestData(Scenario2.java:81)
	at com.mercedesbenz.sechub.integrationtest.internal.AbstractSecHubServerTestScenario.prepareImpl(AbstractSecHubServerTestScenario.java:261)
	at com.mercedesbenz.sechub.integrationtest.internal.AbstractSecHubServerTestScenario.prepare(AbstractSecHubServerTestScenario.java:200)
	at com.mercedesbenz.sechub.integrationtest.api.IntegrationTestSetup$IntegrationTestStatement.evaluate(IntegrationTestSetup.java:195)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:840)

```
When I restart the test multiple times, the user ids etc. are increasing and after some time the test will work again, because a user id will be used which is not existing.

Workaround works... but is very ugly and inconvenient

## Wanted
The growing scenario setup status must be persisted and reused on startup

### Analyze
- `AbstractGrowingSecHubServerTestScenario` uses already `PersistentScenarioTestDataProvider`.
- added trace log parts
- funny: worked some time as it should
- now problem appeared again:
  `0:57:16.407 [main] TRACE c.m.s.i.i.PersistentScenarioTestDataProvider -- File NOT exists: /$myRepoLocation/sechub-integrationtest/build/sechub/integrationtest/scenario-testdata_scenario2.properties`
- means the file has been deleted!

### Sum up
The file is inside the gradle build folder. Means: if a gradle clean task is executed, this build folder will be removed and the file is deleted.
This scenario must be handled by developers on their local machine by themselves.

Inside the code of `PersistentScenarioTestDataProvider` there is also a delete mechanism implemented: when the properties load failed for any reason (any exception) the file was also deleted. 

The property load mechanism shall be more resilient and should do a retry before finally deleting and failing. This will be changed.

**Comment by de-jcup** [comment]
After some time still having such problems, I found it ... :face_exhaling: - `IntegrationTestServerPersistentTestDataCleaner` implemented by myself...

There are good reason for the behavior - e.g. when a build does not call gradle clean or when a developer wants to have similar user ids etc.

Will introduce possibility to disable the auto clean mechanism by spring boot value `sechub.integrationtest.data.autoclean.skip`.

Also logging will be enhanced, so it is clear on (integration test) server startup that a auto clean happens and how to avoid this.
