### ISSUE TITLE
Provide gradle task to format sources

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/sechub#771]
## Situation
In many code reviews source formatting is mentioned and the eclipse auto formatter  must be applied manually to these files. This is necessary but very cumbersome

## Wanted
Per command line there should be one call to format all source codes automatically - with our wanted setup.

## Solution
- We use a dedicated gradle plugin to format the code - e.g. `spotless` which can use eclipse formatter setup. see https://plugins.gradle.org/plugin/com.diffplug.spotless - if not suitable, there are others: see 
https://plugins.gradle.org/search?term=format

We can use
`./gradlew spotlessCheck` to verify

but also
`./gradlew spotlessApply` to automatically format code (currently only Java)

- We introduce also `prepareGitPush` task which dependsOn `spotlessApply`

**Comment by de-jcup** [comment]
Gradle config parts are described at https://github.com/diffplug/spotless/blob/main/plugin-gradle/README.md

**Comment by de-jcup** [comment]
Hmm... groovy formatting makes problems. Having always some eclipse : 
```
Step 'eclipse groovy formatter' found problem in 'build.gradle':

WARNING: Formatting ignored a conflicting text edit
java.lang.IllegalArgumentException: 
WARNING: Formatting ignored a conflicting text edit
        at com.diffplug.spotless.extra.eclipse.groovy.GrEclipseFormatterStepImpl.format(GrEclipseFormatterStepImpl.java:88)
        at jdk.internal.reflect.GeneratedMethodAccessor595.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.diffplug.spotless.extra.groovy.GrEclipseFormatterStep.lambda$apply$0(GrEclipseFormatterStep.java:57)
        at com.diffplug.spotless.FormatterFunc.apply(FormatterFunc.java:32)
...

Was not able to get rid of it, so decided to just turn off groovy inspection by spotless
```

**Comment by de-jcup** [comment]
Remark: It was necessary to execute `spotlessApply` in the final commit, otherwise the build would fail because gradle spotless plugin does now always check inside every build that there are no formatting issues...
